"""dateToDatetime

Revision ID: 6caf2987258a
Revises: 3a1def3468b2
Create Date: 2026-09-15 23:21:13.178260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6caf2987258a'
down_revision: Union[str, Sequence[str], None] = '3a1def3468b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_contribution', sa.Column('occurred_at', sa.DateTime(), nullable=False))
    op.drop_column('goal_contribution', 'date')
    op.add_column('transaction', sa.Column('occurred_at', sa.DateTime(), nullable=False))
    op.drop_column('transaction', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('date', sa.DATE(), nullable=False))
    op.drop_column('transaction', 'occurred_at')
    op.add_column('goal_contribution', sa.Column('date', sa.DATE(), nullable=False))
    op.drop_column('goal_contribution', 'occurred_at')
    # ### end Alembic commands ###
