"""CategoryForeignKeyNullable&budgetMonthDateToDateTime

Revision ID: e8a5fdd886c7
Revises: 6caf2987258a
Create Date: 2026-09-16 02:39:46.159068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a5fdd886c7'
down_revision: Union[str, Sequence[str], None] = '6caf2987258a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_budget_category_id_category'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_budget_category_id_category'), 'category', ['category_id'], ['category_id'], ondelete='SET NULL')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transaction_category_id_category'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transaction_category_id_category'), 'category', ['category_id'], ['category_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transaction_category_id_category'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transaction_category_id_category'), 'category', ['category_id'], ['category_id'])

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_budget_category_id_category'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_budget_category_id_category'), 'category', ['category_id'], ['category_id'])
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('month',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
