"""CategoryGoneBudgetGone

Revision ID: ec1b701148e5
Revises: e8a5fdd886c7
Create Date: 2026-09-16 04:56:48.344625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1b701148e5'
down_revision: Union[str, Sequence[str], None] = 'e8a5fdd886c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_budget_category_id_category'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_budget_category_id_category'), 'category', ['category_id'], ['category_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_budget_category_id_category'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_budget_category_id_category'), 'category', ['category_id'], ['category_id'], ondelete='SET NULL')
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
